version: '3.7'

x-logging_settings:  &logging_settings
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "5"

services:
  nginx:
    image: nginx:1.27.0-alpine-perl
    container_name: nginx
    ports:
      - "${NGINX_PUBPLIC_PORT:-80}:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - grafana
      - prometheus
    networks:
      - monitoring
    restart: always
    <<: *logging_settings
    

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9091:9090"
    networks:
      - monitoring
    restart: always
    <<: *logging_settings    

  grafana:
    image: grafana/grafana:10.4.4-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/plugins:/var/lib/grafana/plugins
      - grafana-data:/var/lib/grafana      

    networks:
      - monitoring
    restart: always
    <<: *logging_settings

  telegraf-metric:
    image: telegraf:1.27-alpine
    container_name: telegraf-metric
    ports:
      - "8080:8080"
      - "9273:9273"
    environment:
      - OUTPUT_METRIC_USER=${TELEGRAF_OUTPUT_METRIC_USER:-admin}
      - OUTPUT_METRIC_PASSWORD=${TELEGRAF_OUTPUT_METRIC_PASSWORD:-dev@123}
      - INPUT_INFLUX_USER=${TELEGRAF_INPUT_INFLUX_USER:-admin}
      - INPUT_INFLUX_PASSWORD=${TELEGRAF_INPUT_INFLUX_PASSWORD:-dev@123}
      - HOSTNAME=${TELEGRAF_HOSTNAME:-telegraf-polling-service}
    volumes:
      - ./telegraf-metric/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - monitoring
    restart: always
    <<: *logging_settings


  telegraf-reporter:
    container_name: telegraf-reporter
    image: telegraf:1.27.4
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MNT=/hostfs/mnt
      - HOST_MOUNT_PREFIX=/hostfs
      - SERIAL=grab
      - INPUT_INFLUX_USER=${TELEGRAF_INPUT_INFLUX_PASSWORD:-dev@123}
      - INPUT_INFLUX_PASSWORD=${TELEGRAF_INPUT_INFLUX_PASSWORD:-dev@123}
    volumes:
      - ./telegraf-reporter/telegraf.conf:/etc/telegraf/telegraf.conf
      - /:/hostfs:ro
      - /mnt:/mnt
    ports:
      - 19273:19273
    restart: always
    <<: *logging_settings



networks:
  monitoring:
    driver: bridge


volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
    
